# Generated by Django 3.1.5 on 2021-01-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210120_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
