# Generated by Django 3.1.5 on 2021-01-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210120_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_id',
            field=models.PositiveIntegerField(verbose_name='Номер заметки'),
        ),
    ]
