# Generated by Django 3.1.5 on 2021-02-03 20:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_auto_20210121_1122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notes',
            unique_together={('user', 'note_id')},
        ),
    ]
